package com.leroy.hostelbackend.module.auth.security;

import com.leroy.hostelbackend.config.JwtConfig;
import com.leroy.hostelbackend.module.user.model.User;
import com.leroy.hostelbackend.module.user.model.UserRole;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

/**
 * Unit tests for {@link JwtService}.
 *
 * <p>Uses a real {@link JwtConfig} (plain POJO, no Spring context needed)
 * rather than mocking it, since generating a real signed token and parsing
 * it back is the only way to actually verify the signing/parsing round
 * trip works — mocking {@code getSecretKey()} would just test that the
 * mock was called, not that tokens are valid.
 */
class JwtServiceTest {

    private static final String SECRET = "test-secret-key-at-least-32-bytes-long-for-hs256!";

    private JwtConfig jwtConfig;
    private JwtService jwtService;

    private User user(UserRole role) {
        var u = new User();
        u.setId(UUID.randomUUID());
        u.setEmail("lexa.doe@ucc.edu.gh");
        u.setPassword("hashed");
        u.setFirstName("Lexa");
        u.setLastName("Doe");
        u.setRole(role);
        return u;
    }

    @BeforeEach
    void setUp() {
        jwtConfig = new JwtConfig();
        jwtConfig.setSecret(SECRET);
        jwtConfig.setTokenExpiration(900);           // 15 minutes
        jwtConfig.setRefreshTokenExpiration(1_209_600); // 14 days
        jwtService = new JwtService(jwtConfig);
    }

    @Test
    @DisplayName("generateAccessToken embeds the user's id, email, name, and role as claims")
    void generateAccessTokenEmbedsExpectedClaims() {
        var user = user(UserRole.STUDENT);

        var jwt = jwtService.generateAccessToken(user);

        assertThat(jwt.getUserId()).isEqualTo(user.getId());
        assertThat(jwt.getRole()).isEqualTo(UserRole.STUDENT);
        assertThat(jwt.isExpired()).isFalse();
    }

    @Test
    @DisplayName("generateAccessToken never embeds the password hash")
    void generateAccessTokenExcludesPassword() {
        var user = user(UserRole.STUDENT);

        var serialized = jwtService.generateAccessToken(user).toString();

        // The password hash must not leak into the token payload under any claim name.
        assertThat(serialized).doesNotContain(user.getPassword());
    }

    @Test
    @DisplayName("generateRefreshToken produces a token that outlives an access token's expiration window")
    void refreshTokenOutlivesAccessToken() {
        var user = user(UserRole.STUDENT);
        jwtConfig.setTokenExpiration(1); // 1 second — expires almost immediately
        jwtService = new JwtService(jwtConfig);

        var accessToken = jwtService.generateAccessToken(user);
        var refreshToken = jwtService.generateRefreshToken(user);

        await(1200);

        assertThat(accessToken.isExpired()).isTrue();
        assertThat(refreshToken.isExpired()).isFalse();
    }

    @Test
    @DisplayName("parseToken round-trips a token generated by this same service")
    void parseTokenRoundTripsGeneratedToken() {
        var user = user(UserRole.MANAGER);
        var serialized = jwtService.generateAccessToken(user).toString();

        var parsed = jwtService.parseToken(serialized);

        assertThat(parsed).isNotNull();
        assertThat(parsed.getUserId()).isEqualTo(user.getId());
        assertThat(parsed.getRole()).isEqualTo(UserRole.MANAGER);
        assertThat(parsed.isExpired()).isFalse();
    }

    @Test
    @DisplayName("parseToken returns null for a structurally malformed token")
    void parseTokenReturnsNullForMalformedToken() {
        assertThat(jwtService.parseToken("not-a-jwt-at-all")).isNull();
    }

    @Test
    @DisplayName("parseToken returns null for a token signed with a different secret")
    void parseTokenReturnsNullForWrongSignature() {
        var otherConfig = new JwtConfig();
        otherConfig.setSecret("a-completely-different-secret-key-of-32-bytes!!");
        otherConfig.setTokenExpiration(900);
        var otherService = new JwtService(otherConfig);
        var user = user(UserRole.STUDENT);

        var tokenSignedWithOtherKey = otherService.generateAccessToken(user).toString();

        assertThat(jwtService.parseToken(tokenSignedWithOtherKey)).isNull();
    }

    @Test
    @DisplayName("parseToken returns null for a token whose payload has been tampered with")
    void parseTokenReturnsNullForTamperedPayload() {
        var user = user(UserRole.STUDENT);
        var serialized = jwtService.generateAccessToken(user).toString();
        var parts = serialized.split("\\.");
        // Flip the last character of the payload segment to invalidate the signature.
        var tamperedPayload = parts[1].substring(0, parts[1].length() - 1)
                + (parts[1].endsWith("A") ? "B" : "A");
        var tampered = parts[0] + "." + tamperedPayload + "." + parts[2];

        assertThat(jwtService.parseToken(tampered)).isNull();
    }

    @Test
    @DisplayName("parseToken currently throws (not returns null) for an empty string — see note below")
    void parseTokenThrowsForEmptyString() {
        // NOTE: parseToken's Javadoc promises null "on parse failure", and every
        // other malformed-input case in this file does return null — but this one
        // doesn't. jjwt's own Assert.hasText() rejects a null/empty token with a
        // plain IllegalArgumentException *before* real JWT parsing begins, and
        // that exception type is not a JwtException, so parseToken's
        // `catch (JwtException e)` doesn't catch it. In production this token
        // comes from stripping "Bearer " off the Authorization header in
        // JwtAuthenticationFilter, so a request with header value "Bearer "
        // (empty token) would currently surface as an uncaught exception rather
        // than the clean 401 every other malformed-token case produces. Pinning
        // the actual behavior here rather than the assumed one; the one-line fix
        // if you want it is either an early blank-check in parseToken or widening
        // the catch to `catch (JwtException | IllegalArgumentException e)`.
        assertThatThrownBy(() -> jwtService.parseToken(""))
                .isInstanceOf(IllegalArgumentException.class);
    }

    /** Small sleep helper — used only to straddle a real (short) expiration boundary. */
    private static void await(long millis) {
        try {
            Thread.sleep(millis);
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
            throw new IllegalStateException(e);
        }
    }
}
